// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwK9a3h4WdgXqL0e12AnyVk2LnsEuxjQ',
    appId: '1:1081210452379:web:280326d98a4755165f893e',
    messagingSenderId: '1081210452379',
    projectId: 'furniture-app-833d5',
    authDomain: 'furniture-app-833d5.firebaseapp.com',
    storageBucket: 'furniture-app-833d5.appspot.com',
    measurementId: 'G-VHRTQPXKV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGnd8L8ewqAp9_Ci7CNdVFecDNfII2RmA',
    appId: '1:1081210452379:android:37434c05bfcecc995f893e',
    messagingSenderId: '1081210452379',
    projectId: 'furniture-app-833d5',
    storageBucket: 'furniture-app-833d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFb5_t-tWBOixHMSTmd9gfGNpNOqibBus',
    appId: '1:1081210452379:ios:9fffb4f6f233186e5f893e',
    messagingSenderId: '1081210452379',
    projectId: 'furniture-app-833d5',
    storageBucket: 'furniture-app-833d5.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFb5_t-tWBOixHMSTmd9gfGNpNOqibBus',
    appId: '1:1081210452379:ios:a66028a6d4d21ce55f893e',
    messagingSenderId: '1081210452379',
    projectId: 'furniture-app-833d5',
    storageBucket: 'furniture-app-833d5.appspot.com',
    iosBundleId: 'com.example.shop.RunnerTests',
  );
}
